# -*- coding: utf-8 -*-
"""Running Deterministic version.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVhzMhTBu_ic-EoXiOsoRFIDyUyZLtOz
"""

from google.colab import drive
drive.mount('/content/mydrive/')

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/mydrive/MyDrive/.SVM"

"""# Installation"""

!pip install numpy pandas scipy matplotlib scikit-learn cvxpy joblib

!pip install clarabel

!pip install ucimlrepo

"""# dataset loading

"arrhythmia": {
        "csv_name": "arrhythmia.csv",
        "data_transform": "none",
        "kernel": "gaussian_rbf",
    },
    "parkinsons": {
        "csv_name": "parkinsons.csv",
        "data_transform": "minmax",
        "kernel": "hom_linear",
    },
    "heart_disease": {
        "csv_name": "heart_disease.csv",
        "data_transform": "standardization",
        "kernel": "inhom_linear",
    },
    "dermatology": {
        "csv_name": "dermatology.csv",
        "data_transform": "none",
        "kernel": "inhom_quadratic",
    },
    "climate_model_crashes": {
        "csv_name": "climate_model_crashes.csv",
        "data_transform": "none",
        "kernel": "hom_linear",
    },
    "breast_cancer_diagnostic": {
        "csv_name": "breast_cancer_diagnostic.csv",
        "data_transform": "minmax",
        "kernel": "inhom_quadratic",
    },
    "breast_cancer": {
        "csv_name": "breast_cancer.csv",
        "data_transform": "standardization",
        "kernel": "hom_linear",
    },
    "blood_transfusion": {
        "csv_name": "blood_transfusion.csv",
        "data_transform": "standardization",
        "kernel": "inhom_cubic",
    },
    "mammographicmass_binary": {
        "csv_name": "mammographicmass_binary.csv",
        "data_transform": "standardization",
        "kernel": "inhom_quadratic",
    },
    "qsar_biodegradation": {
        "csv_name": "qsar_biodegradation.csv",
        "data_transform": "minmax",
        "kernel": "gaussian_rbf",
    },
}
"""

import os
import pandas as pd
from ucimlrepo import fetch_ucirepo

# Dataset IDs
# 174 = Parkinsons
# 45  = Heart Disease
# 33  = Dermatology
# 17  = Breast Cancer Wisconsin (Diagnostic)
# 14  = Breast Cancer
# 176 = blood_transfusion

# Fetch dataset
dataset = fetch_ucirepo(id=176)

# Features and labels
X = dataset.data.features.copy()
y = dataset.data.targets.copy()

# Rename feature columns: DATA1, DATA2, ...
X.columns = [f"DATA{i+1}" for i in range(X.shape[1])]

# Rename target column(s)
if y.shape[1] == 1:
    y.columns = ["Class"]

    # Convert string labels to integer labels if necessary
    if not pd.api.types.is_numeric_dtype(y["Class"]):
        y["Class"], uniques = pd.factorize(y["Class"])

        print("\nClass label mapping:")
        for idx, label in enumerate(uniques):
            print(f"  {label} -> {idx}")

else:
    y.columns = [f"Class{i+1}" for i in range(y.shape[1])]

# Combine features and target
df = pd.concat([X, y], axis=1)

# Create output directory
output_dir = "dataset"
os.makedirs(output_dir, exist_ok=True)

# Save CSV
output_path = os.path.join(output_dir, "blood_transfusion.csv")
df.to_csv(output_path, index=False)

print(f"\nDataset saved to: {output_path}")
print(f"Shape: {df.shape}")

# Metadata
print("\nMetadata:")
print(dataset.metadata)

print("\nVariables:")
print(dataset.variables)

"""# Binary
# Determinstic (mammographicmass_binary.csv)
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd "1. Deterministic and binary"

!python main_deterministic_binary.py --dataset mammographicmass_binary

"""# Determinstic (parkinsons.csv)"""

!python main_deterministic_binary.py --dataset parkinsons

"""# Determinstic (breast_cancer_diagnostic.csv)"""

!python main_deterministic_binary.py --dataset breast_cancer_diagnostic

"""# Determinstic (blood_transfusion.csv)"""

!python main_deterministic_binary.py --dataset blood_transfusion

!rm -rf "/content/mydrive/MyDrive/.SVM/1. Deterministic and binary/results/breast_cancer"

"""# Multi Class
# Determinstic (iris_multiclass.csv)
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/mydrive/MyDrive/.SVM"

# Commented out IPython magic to ensure Python compatibility.
# %cd "2. Deterministic and multiclass"

!mkdir dataset

!mv iris_multiclass.csv dataset/

!python main_deterministic_multiclass.py --dataset iris